/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
===============================================================================
*/


-- Find the Total Number of Customers by Countries
SELECT 
country As Country, COUNT(customer_id) As Total_Customers
from gold.dim_customers
GROUP BY country
order by COUNT(customer_id) desc



-- Find the Total Customers by Gender
SELECT 
gender As Gender, COUNT(customer_id) As Total_Customers
from gold.dim_customers
GROUP BY gender
order by COUNT(customer_id) desc



-- Find Total Products by Category
SELECT 
category As Category, COUNT(product_id) As Total_Products
from gold.dim_products
GROUP BY category
order by Total_Products desc



-- What is the Average Cost in each Category
SELECT 
category As Category, AVG(cost) As Avearge_Cost
from gold.dim_products
GROUP BY category
order by Avearge_Cost desc



-- What is the Total Revenue generated in each Category
SELECT 
p.category As Category,
SUM(f.sales_amount) As Total_Revenue
from gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
order by Total_Revenue desc



-- What is the Total Revenue generated by each Customer
SELECT 
c.customer_key As Customer_Id,
c.first_name As First_Name,
c.last_name As Last_Name,
SUM(f.sales_amount) As Total_Sales
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
order by Total_Sales desc



-- What is the Distribution of Sold Items across Countries
SELECT 
c.country As Country,
SUM(f.quantity) As Total_Sold_Items
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
order by Total_Sold_Items desc
